{
  "hash": "ea2c066b52d2f82d076a9d3f5269b078",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 1: Census Data Quality for Policy Decisions\"\nsubtitle: \"Evaluating Data Reliability for Algorithmic Decision-Making\"\nauthor: \"Annalise Abraham\"\ndate: \"September 28 2025\"\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\nexecute:\n  warning: false\n  message: false\n---\n\n# Assignment Overview\n\n## Scenario\n\nYou are a data analyst for the **PA Department of Human Services**. The department is considering implementing an algorithmic system to identify communities that should receive priority for social service funding and outreach programs. Your supervisor has asked you to evaluate the quality and reliability of available census data to inform this decision.\n\nDrawing on our Week 2 discussion of algorithmic bias, you need to assess not just what the data shows, but how reliable it is and what communities might be affected by data quality issues.\n\n## Learning Objectives\n\n- Apply dplyr functions to real census data for policy analysis\n- Evaluate data quality using margins of error \n- Connect technical analysis to algorithmic decision-making\n- Identify potential equity implications of data reliability issues\n- Create professional documentation for policy stakeholders\n\n## Submission Instructions\n\n**Submit by posting your updated portfolio link on Canvas.** Your assignment should be accessible at `your-portfolio-url/assignments/assignment_1/`\n\nMake sure to update your `_quarto.yml` navigation to include this assignment under an \"Assignments\" menu.\n\n# Part 1: Portfolio Integration\n\nCreate this assignment in your portfolio repository under an `assignments/assignment_1/` folder structure. Update your navigation menu to include:\n\n```\n- text: Assignments\n  menu:\n    - href: assignments/assignment_1/your_file_name.qmd\n      text: \"Assignment 1: Census Data Exploration\"\n```\nIf there is a special character like comma, you need use double quote mark so that the quarto can identify this as text\n\n# Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages (hint: you need tidycensus, tidyverse, and knitr)\n\nlibrary(tidycensus)\nlibrary(tidyverse)\nlibrary(knitr)\ncensus_api_key(\"7f3237778c134da68ede6b2dc985410b3788e258\")\n\n# Set your Census API key\n\n# Choose your state for analysis - assign it to a variable called my_state\n```\n:::\n\n\n**State Selection:** I have chosen **[Pennsylvania]** for this analysis because: [it's where I grew up and where I have lived my entire life!]\n\n# Part 2: County-Level Resource Assessment\n\n## 2.1 Data Retrieval\n\n**Your Task:** Use `get_acs()` to retrieve county-level data for your chosen state.\n\n**Requirements:**\n- Geography: county level\n- Variables: median household income (B19013_001) and total population (B01003_001)  \n- Year: 2022\n- Survey: acs5\n- Output format: wide\n\n**Hint:** Remember to give your variables descriptive names using the `variables = c(name = \"code\")` syntax.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your get_acs() code here\n\npa_data <- get_acs(\n  geography = \"county\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    median_income = \"B19013_001\"\n  ),\n  state = \"PA\",\n  year = 2022,\n  output = \"wide\"  # Makes analysis easier\n)\n\n# Clean the county names to remove state name and \"County\" \n# Hint: use mutate() with str_remove()\n\npa_data <- pa_data %>%\n  mutate(\n    NAME = str_remove(NAME, \", Pennsylvania\"),  # remove state name\n    NAME = str_remove(NAME, \" County\")          # remove \"County\"\n  )\n\n# Display the first few rows\n```\n:::\n\n\n## 2.2 Data Quality Assessment\n\n**Your Task:** Calculate margin of error percentages and create reliability categories.\n\n**Requirements:**\n- Calculate MOE percentage: (margin of error / estimate) * 100\n- Create reliability categories:\n  - High Confidence: MOE < 5%\n  - Moderate Confidence: MOE 5-10%  \n  - Low Confidence: MOE > 10%\n- Create a flag for unreliable estimates (MOE > 10%)\n\n**Hint:** Use `mutate()` with `case_when()` for the categories.\n\n::: {.cell}\n\n```{.r .cell-code}\npaa_data_alt <- pa_data %>%\n  mutate(\n    moe_pct = (median_incomeM / median_incomeE) * 100,\n    reliability = case_when(\n      moe_pct < 5 ~ \"High Confidence\",\n      moe_pct >= 5 & moe_pct <= 10 ~ \"Moderate Confidence\",\n      moe_pct > 10 ~ \"Low Confidence\"\n    ),\n    unreliable_flag = moe_pct > 10\n  )\n\nls()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"pa_data\"      \"paa_data_alt\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate MOE percentage and reliability categories using mutate()\n\n# Create a summary showing count of counties in each reliability category\n# Hint: use count() and mutate() to add percentages\n\n\n\nreliability_summary <- paa_data_alt %>%\n  count(reliability) %>%\n  mutate(\n    pct = n / sum(n) * 100\n  )\n  \nls()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"pa_data\"             \"paa_data_alt\"        \"reliability_summary\"\n```\n\n\n:::\n:::\n\n## 2.3 High Uncertainty Counties\n\n\"**Your Task:** Identify the 5 counties with the highest MOE percentages.\"\n\n\"**Requirements:**\n- Sort by MOE percentage (highest first)\n- Select the top 5 counties\n- Display: county name, median income, margin of error, MOE percentage, reliability category\n- Format as a professional table using `kable()`\n\n**Hint:** Use `arrange()`, `slice()`, and `select()` functions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create table of top 5 counties by MOE percentage\n\ntop5_moe <- paa_data_alt %>%\n  arrange(desc(moe_pct)) %>%\n  slice_head(n = 5) %>%\n  select(\n    County = NAME,\n    \"Median Income\" = median_incomeE,\n    \"Margin of Error\" = median_incomeM,\n    \"MOE %\" = moe_pct,\n    Reliability = reliability\n  )\n\n\n# Format as table with kable() - include appropriate column names and caption\n\nkable(\n  top5_moe,\n  caption = \"Top 5 Counties with Highest MOE Percentages\",\n  digits = 1,\n  format.args = list(big.mark = \",\")\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 5 Counties with Highest MOE Percentages\n\n|County   | Median Income| Margin of Error| MOE %|Reliability         |\n|:--------|-------------:|---------------:|-----:|:-------------------|\n|Forest   |        46,188|           4,612|  10.0|Moderate Confidence |\n|Sullivan |        62,910|           5,821|   9.3|Moderate Confidence |\n|Union    |        64,914|           4,753|   7.3|Moderate Confidence |\n|Montour  |        72,626|           5,146|   7.1|Moderate Confidence |\n|Elk      |        61,672|           4,091|   6.6|Moderate Confidence |\n\n\n:::\n:::\n\n**Data Quality Commentary:**\n\n[Write 2-3 sentences explaining what these results mean for algorithmic decision-making. Consider: Which counties might be poorly served by algorithms that rely on this income data? What factors might contribute to higher uncertainty? - Counties with lower confidence levels have less reliable data. A large range in the median income values or a small sample size could lead to higher levels of uncertainty.]\"\n\n# Part 3: Neighborhood-Level Analysis\n\n## 3.1 Focus Area Selection\n\n\"**Your Task:** Select 2-3 counties from your reliability analysis for detailed tract-level study.\"\n\n\"**Strategy:** Choose counties that represent different reliability levels (e.g., 1 high confidence, 1 moderate, 1 low confidence) to compare how data quality varies.\"\n\n\n# Use filter() to select 2-3 counties from your county_reliability data\n# Store the selected counties in a variable called selected_counties\n\n# Display the selected counties with their key characteristics\n# Show: county name, median income, MOE percentage, reliability category\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_counties <- paa_data_alt %>%\n  filter(NAME %in% c(\"Forest\", \n                     \"Allegheny\")) %>%\n  select(\n    County = NAME,\n    `Median Income` = median_incomeE,\n    `MOE %` = moe_pct,\n    Reliability = reliability\n  )\n\nselected_counties                   \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  County    `Median Income` `MOE %` Reliability        \n  <chr>               <dbl>   <dbl> <chr>              \n1 Allegheny           72537    1.20 High Confidence    \n2 Forest              46188    9.99 Moderate Confidence\n```\n\n\n:::\n:::\n\n**Comment on the output:** [Allegheny County has a median income of $72537 and a margin of error of 1.2% while Forest County has a median income of $46188 and a margin of error of 10%.]\n\n## 3.2 Tract-Level Demographics\n\n**Your Task:** Get demographic data for census tracts in your selected counties.\n\n**Requirements:**\n- Geography: tract level\n- Variables: white alone (B03002_003), Black/African American (B03002_004), Hispanic/Latino (B03002_012), total population (B03002_001)\n- Use the same state and year as before\n- Output format: wide\n- **Challenge:** You'll need county codes, not names. Look at the GEOID patterns in your county data for hints.\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define your race/ethnicity variables with descriptive names\n\n# Use get_acs() to retrieve tract-level data\n# Hint: You may need to specify county codes in the county parameter\n\n# Calculate percentage of each group using mutate()\n# Create percentages for white, Black, and Hispanic populations\n\n# Add readable tract and county name columns using str_extract() or similar\n\n\nlibrary(stringr)\n\nrace_vars <- c(\n  total_pop = \"B03002_001\",\n  white_alone = \"B03002_003\",\n  black_alone = \"B03002_004\",\n  hispanic = \"B03002_012\"\n)\n\n# get tracts for Allegheny County (003) and Forest County (053) in PA\ntract_demographics <- get_acs(\n  geography = \"tract\",\n  state = \"42\",             # Pennsylvania FIPS\n  county = c(\"003\", \"053\"), # county codes\n  variables = race_vars,\n  year = 2022,              # use same year as before\n  survey = \"acs5\",\n  output = \"wide\"\n) %>%\n  # Calculate percentages\n  mutate(\n    pct_white = 100 * white_aloneE / total_popE,\n    pct_black = 100 * black_aloneE / total_popE,\n    pct_hispanic = 100 * hispanicE / total_popE\n  ) %>%\n  # Extract readable county and tract codes from GEOID\n  mutate(\n    state_fips = str_sub(GEOID, 1, 2),\n    county_fips = str_sub(GEOID, 3, 5),\n    tract_code = str_sub(GEOID, 6, 11)\n  )\n```\n:::\n\n## 3.3 Demographic Analysis\n\n**Your Task:** Analyze the demographic patterns in your selected areas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find the tract with the highest percentage of Hispanic/Latino residents\n# Hint: use arrange() and slice() to get the top tract\n\ntop_hispanic_tract <- tract_demographics %>%\n  arrange(desc(pct_hispanic)) %>%\n  slice(1) %>%\n  select(NAME, pct_white, pct_black, pct_hispanic)\n\n# Calculate average demographics by county using group_by() and summarize()\n# Show: number of tracts, average percentage for each racial/ethnic group\n\ncounty_summary <- tract_demographics %>%\n  group_by(county_fips) %>%   # use county code\n  summarize(\n    n_tracts = n(),\n    avg_pct_white = mean(pct_white, na.rm = TRUE),\n    avg_pct_black = mean(pct_black, na.rm = TRUE),\n    avg_pct_hispanic = mean(pct_hispanic, na.rm = TRUE)\n  ) %>%\n  ungroup()\n\n# Create a nicely formatted table of your results using kable()\n\ncounty_summary %>%\n  kable(digits = 1, caption = \"Average Demographics by County (ACS 2022 5-year)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Average Demographics by County (ACS 2022 5-year)\n\n|county_fips | n_tracts| avg_pct_white| avg_pct_black| avg_pct_hispanic|\n|:-----------|--------:|-------------:|-------------:|----------------:|\n|003         |      394|          74.5|          15.4|              2.4|\n|053         |        2|          71.2|          13.6|              7.4|\n\n\n:::\n:::\n\n# Part 4: Comprehensive Data Quality Evaluation\n\n## 4.1 MOE Analysis for Demographic Variables\n\n**Your Task:** Examine margins of error for demographic variables to see if some communities have less reliable data.\n\n**Requirements:**\n- Calculate MOE percentages for each demographic variable\n- Flag tracts where any demographic variable has MOE > 15%\n- Create summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate MOE percentages for white, Black, and Hispanic variables\n# Hint: use the same formula as before (margin/estimate * 100)\n\n# Create a flag for tracts with high MOE on any demographic variable\n# Use logical operators (| for OR) in an ifelse() statement\n\n# Create summary statistics showing how many tracts have data quality issues\n\ndemographic_moe <- tract_demographics %>%\n  # 1. Calculate MOE percentages\n  mutate(\n    moe_white = 100 * white_aloneM / white_aloneE,\n    moe_black = 100 * black_aloneM / black_aloneE,\n    moe_hispanic = 100 * hispanicM / hispanicE\n  ) %>%\n  # 2. Replace Inf with NA\n  mutate(\n    across(starts_with(\"moe_\"), ~ ifelse(is.infinite(.), NA, .))\n  ) %>%\n  # 3. Flag high MOE tracts (any variable > 15%)\n  mutate(\n    high_moe_flag = ifelse(\n      moe_white > 15 | moe_black > 15 | moe_hispanic > 15,\n      TRUE, FALSE\n    )\n  )\n\n# 3. Summary statistics\nmoe_summary <- demographic_moe %>%\n  summarize(\n    total_tracts = n(),\n    tracts_high_moe = sum(high_moe_flag, na.rm = TRUE),\n    pct_high_moe = 100 * tracts_high_moe / total_tracts,\n    avg_moe_white = mean(moe_white, na.rm = TRUE),\n    avg_moe_black = mean(moe_black, na.rm = TRUE),\n    avg_moe_hispanic = mean(moe_hispanic, na.rm = TRUE)\n  )\n```\n:::\n\n## 4.2 Pattern Analysis\n\n\"**Your Task:** Investigate whether data quality problems are randomly distributed or concentrated in certain types of communities.\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Group tracts by whether they have high MOE issues\n# Calculate average characteristics for each group:\n# - population size, demographic percentages\n\n# Use group_by() and summarize() to create this comparison\n# Create a professional table showing the patterns\n\npattern_analysis <- demographic_moe %>%\n  group_by(high_moe_flag) %>%\n  summarize(\n    n_tracts = n(),\n    avg_population = mean(total_popE, na.rm = TRUE),\n    avg_pct_white = mean(pct_white, na.rm = TRUE),\n    avg_pct_black = mean(pct_black, na.rm = TRUE),\n    avg_pct_hispanic = mean(pct_hispanic, na.rm = TRUE)\n  ) %>%\n  ungroup()\n\n# Nicely formatted comparison table\n\npattern_analysis %>%\n  kable(\n    digits = 1,\n    caption = \"Comparison of Tracts by Data Quality (High MOE vs. Reliable)\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Comparison of Tracts by Data Quality (High MOE vs. Reliable)\n\n|high_moe_flag | n_tracts| avg_population| avg_pct_white| avg_pct_black| avg_pct_hispanic|\n|:-------------|--------:|--------------:|-------------:|-------------:|----------------:|\n|TRUE          |      387|         3231.3|          74.4|          15.4|              2.4|\n|NA            |        9|          193.2|          95.2|           0.0|              0.0|\n\n\n:::\n:::\n\n\"**Pattern Analysis:** [Describe any patterns you observe. Do certain types of communities have less reliable data? What might explain this? All the census tracts I looked at had MOE issues. The Black and Latino population data did have higher MOEs in general, perhaps because they had a smaller sample size. - Would appreciate feedback on this!]\"\n\n\n# Part 5: Policy Recommendations\n\n## 5.1 Analysis Integration and Professional Summary\n\n\"**Your Task:** Write an executive summary that integrates findings from all four analyses.\n\n**Executive Summary Requirements:**\n1. **Overall Pattern Identification**: What are the systematic patterns across all your analyses?\n2. **Equity Assessment**: Which communities face the greatest risk of algorithmic bias based on your findings?\n3. **Root Cause Analysis**: What underlying factors drive both data quality issues and bias risk?\n4. **Strategic Recommendations**: What should the Department implement to address these systematic issues?\n\n**Executive Summary:**\n\n[Our analysis of tract-level ACS data reveals that data quality problems are not randomly distributed across communities but follow clear and systematic patterns. Tracts with smaller populations consistently show higher margins of error for race and ethnicity variables, often exceeding the 15% threshold we defined for reliability concerns. In addition, tracts with higher shares of minority residents—particularly Hispanic and Black populations—are more likely to have elevated uncertainty in their demographic estimates. These findings indicate that the reliability of ACS data is unevenly distributed, with some communities consistently at a disadvantage.\n\nThis uneven distribution of reliability has important equity implications. Communities that are rural, sparsely populated, or home to significant minority populations face the greatest risk of algorithmic bias. If public agencies or partner organizations treat ACS point estimates as precise without accounting for uncertainty, decisions around resource allocation, service provision, or equity monitoring could systematically disadvantage these groups. In practice, the populations already most vulnerable to underinvestment and underrepresentation in surveys are also the ones most likely to be mischaracterized by models built on noisy or unstable data.\n\nThe root causes of these data quality disparities lie in both statistical and structural factors. Survey sampling variability is highest where population counts are low, leading to inflated margins of error in small tracts. At the same time, nonresponse and undercoverage are more common in communities with higher proportions of immigrants, renters, and low-income households. These factors compound one another, producing both unreliable estimates and heightened risk of algorithmic bias. The patterns observed are thus not only statistical artifacts but reflections of deeper structural inequities in data collection and representation.\n\nTo address these challenges, the Department should adopt a multi-layered strategy. In the short term, all products and models should explicitly incorporate margins of error, with unreliable tracts either flagged, down-weighted, or aggregated to higher levels of geography. In the medium term, statistical smoothing methods and fairness audits can reduce the impact of noisy inputs on decision-making. Over the long term, investment in targeted data collection and stronger transparency requirements will be necessary to ensure that all communities are represented with sufficient accuracy. By embedding data reliability standards into analytic workflows, the Department can both mitigate bias and build greater trust in its use of demographic data.]\n\n## 6.3 Specific Recommendations\n\n**Your Task:** Create a decision framework for algorithm implementation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a summary table using your county reliability data\n# Include: county name, median income, MOE percentage, reliability category\n\n# Add a new column with algorithm recommendations using case_when():\n# - High Confidence: \"Safe for algorithmic decisions\"\n# - Moderate Confidence: \"Use with caution - monitor outcomes\"  \n# - Low Confidence: \"Requires manual review or additional data\"\n\n# Format as a professional table with kable()\"\n\n\ncounty_summary <- paa_data_alt %>%\n  select(\n    County = NAME,\n    `Median Income` = median_incomeE,\n    `MOE %` = moe_pct,\n    Reliability = reliability\n  ) %>%\n  mutate(\n    Recommendation = case_when(\n      Reliability == \"High Confidence\" ~ \"Safe for algorithmic decisions\",\n      Reliability == \"Moderate Confidence\" ~ \"Use with caution - monitor outcomes\",\n      Reliability == \"Low Confidence\" ~ \"Requires manual review or additional data\",\n      TRUE ~ \"Unclassified\"\n    )\n  )\n\n# Nicely formatted table\ncounty_summary %>%\n  kable(\n    digits = 1,\n    caption = \"County Reliability and Algorithmic Recommendations\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: County Reliability and Algorithmic Recommendations\n\n|County         | Median Income| MOE %|Reliability         |Recommendation                      |\n|:--------------|-------------:|-----:|:-------------------|:-----------------------------------|\n|Adams          |         78975|   4.2|High Confidence     |Safe for algorithmic decisions      |\n|Allegheny      |         72537|   1.2|High Confidence     |Safe for algorithmic decisions      |\n|Armstrong      |         61011|   3.6|High Confidence     |Safe for algorithmic decisions      |\n|Beaver         |         67194|   2.3|High Confidence     |Safe for algorithmic decisions      |\n|Bedford        |         58337|   4.5|High Confidence     |Safe for algorithmic decisions      |\n|Berks          |         74617|   1.6|High Confidence     |Safe for algorithmic decisions      |\n|Blair          |         59386|   3.5|High Confidence     |Safe for algorithmic decisions      |\n|Bradford       |         60650|   3.6|High Confidence     |Safe for algorithmic decisions      |\n|Bucks          |        107826|   1.4|High Confidence     |Safe for algorithmic decisions      |\n|Butler         |         82932|   2.6|High Confidence     |Safe for algorithmic decisions      |\n|Cambria        |         54221|   3.3|High Confidence     |Safe for algorithmic decisions      |\n|Cameron        |         46186|   5.6|Moderate Confidence |Use with caution - monitor outcomes |\n|Carbon         |         64538|   5.3|Moderate Confidence |Use with caution - monitor outcomes |\n|Centre         |         70087|   2.8|High Confidence     |Safe for algorithmic decisions      |\n|Chester        |        118574|   1.7|High Confidence     |Safe for algorithmic decisions      |\n|Clarion        |         58690|   4.4|High Confidence     |Safe for algorithmic decisions      |\n|Clearfield     |         56982|   2.8|High Confidence     |Safe for algorithmic decisions      |\n|Clinton        |         59011|   3.9|High Confidence     |Safe for algorithmic decisions      |\n|Columbia       |         59457|   3.8|High Confidence     |Safe for algorithmic decisions      |\n|Crawford       |         58734|   3.9|High Confidence     |Safe for algorithmic decisions      |\n|Cumberland     |         82849|   2.2|High Confidence     |Safe for algorithmic decisions      |\n|Dauphin        |         71046|   2.3|High Confidence     |Safe for algorithmic decisions      |\n|Delaware       |         86390|   1.5|High Confidence     |Safe for algorithmic decisions      |\n|Elk            |         61672|   6.6|Moderate Confidence |Use with caution - monitor outcomes |\n|Erie           |         59396|   2.6|High Confidence     |Safe for algorithmic decisions      |\n|Fayette        |         55579|   4.2|High Confidence     |Safe for algorithmic decisions      |\n|Forest         |         46188|  10.0|Moderate Confidence |Use with caution - monitor outcomes |\n|Franklin       |         71808|   3.0|High Confidence     |Safe for algorithmic decisions      |\n|Fulton         |         63153|   3.6|High Confidence     |Safe for algorithmic decisions      |\n|Greene         |         66283|   6.4|Moderate Confidence |Use with caution - monitor outcomes |\n|Huntingdon     |         61300|   4.7|High Confidence     |Safe for algorithmic decisions      |\n|Indiana        |         57170|   4.6|High Confidence     |Safe for algorithmic decisions      |\n|Jefferson      |         56607|   3.4|High Confidence     |Safe for algorithmic decisions      |\n|Juniata        |         61915|   4.8|High Confidence     |Safe for algorithmic decisions      |\n|Lackawanna     |         63739|   2.6|High Confidence     |Safe for algorithmic decisions      |\n|Lancaster      |         81458|   1.8|High Confidence     |Safe for algorithmic decisions      |\n|Lawrence       |         57585|   3.1|High Confidence     |Safe for algorithmic decisions      |\n|Lebanon        |         72532|   2.7|High Confidence     |Safe for algorithmic decisions      |\n|Lehigh         |         74973|   2.0|High Confidence     |Safe for algorithmic decisions      |\n|Luzerne        |         60836|   2.4|High Confidence     |Safe for algorithmic decisions      |\n|Lycoming       |         63437|   4.4|High Confidence     |Safe for algorithmic decisions      |\n|McKean         |         57861|   4.7|High Confidence     |Safe for algorithmic decisions      |\n|Mercer         |         57353|   3.6|High Confidence     |Safe for algorithmic decisions      |\n|Mifflin        |         58012|   3.4|High Confidence     |Safe for algorithmic decisions      |\n|Monroe         |         80656|   3.2|High Confidence     |Safe for algorithmic decisions      |\n|Montgomery     |        107441|   1.3|High Confidence     |Safe for algorithmic decisions      |\n|Montour        |         72626|   7.1|Moderate Confidence |Use with caution - monitor outcomes |\n|Northampton    |         82201|   1.9|High Confidence     |Safe for algorithmic decisions      |\n|Northumberland |         55952|   2.7|High Confidence     |Safe for algorithmic decisions      |\n|Perry          |         76103|   3.2|High Confidence     |Safe for algorithmic decisions      |\n|Philadelphia   |         57537|   1.4|High Confidence     |Safe for algorithmic decisions      |\n|Pike           |         76416|   4.9|High Confidence     |Safe for algorithmic decisions      |\n|Potter         |         56491|   4.4|High Confidence     |Safe for algorithmic decisions      |\n|Schuylkill     |         63574|   2.4|High Confidence     |Safe for algorithmic decisions      |\n|Snyder         |         65914|   5.6|Moderate Confidence |Use with caution - monitor outcomes |\n|Somerset       |         57357|   2.8|High Confidence     |Safe for algorithmic decisions      |\n|Sullivan       |         62910|   9.3|Moderate Confidence |Use with caution - monitor outcomes |\n|Susquehanna    |         63968|   3.1|High Confidence     |Safe for algorithmic decisions      |\n|Tioga          |         59707|   3.2|High Confidence     |Safe for algorithmic decisions      |\n|Union          |         64914|   7.3|Moderate Confidence |Use with caution - monitor outcomes |\n|Venango        |         59278|   3.4|High Confidence     |Safe for algorithmic decisions      |\n|Warren         |         57925|   5.2|Moderate Confidence |Use with caution - monitor outcomes |\n|Washington     |         74403|   2.4|High Confidence     |Safe for algorithmic decisions      |\n|Wayne          |         59240|   4.8|High Confidence     |Safe for algorithmic decisions      |\n|Westmoreland   |         69454|   2.0|High Confidence     |Safe for algorithmic decisions      |\n|Wyoming        |         67968|   3.9|High Confidence     |Safe for algorithmic decisions      |\n|York           |         79183|   1.8|High Confidence     |Safe for algorithmic decisions      |\n\n\n:::\n:::\n\n**Key Recommendations**\n\n**Your Task** Use your analysis results to provide specific guidance to the department.\n\n1. **Counties suitable for immediate algorithmic implementation:** [Counties with high confidence data are appropriate because they have low margins of error.]\n\n2. **Counties requiring additional oversight:** [List counties with moderate confidence data and describe what kind of monitoring would be needed. The counties with moderate confidence data include Cameron, Carbon, Elk, Forest, Greene, Montour, Snyder, Sullivan, Union, and Warren counties. Monitoring could include tracking discrepancies or unusual trends or flagging certain results for human review.]\n\n3. **Counties needing alternative approaches:** None\n\n## Questions for Further Investigation\n\n[List 2-3 questions that your analysis raised that you'd like to explore further in future assignments. Consider questions about spatial patterns, time trends, or other demographic factors.\n\nHow can data be assessed if all tracts have high margins of error? How can we judge whether certain issues or traits are spatially signifigant?]\n\n# Technical Notes\n\n**Data Sources:** \n- U.S. Census Bureau, American Community Survey 2018-2022 5-Year Estimates\n- Retrieved via tidycensus R package on [9.29.25]\n\n**Reproducibility:** \n- All analysis conducted in R version [your version]\n- Census API key required for replication\n- Complete code and documentation available at: [your portfolio URL]\n\n**Methodology Notes:**\n[Describe any decisions you made about data processing, county selection, or analytical choices that might affect reproducibility]\n\n**Limitations:**\n[Note any limitations in your analysis - sample size issues, geographic scope, temporal factors, etc.]\"\n\n---\n\n\"## Submission Checklist\n\nBefore submitting your portfolio link on Canvas:\n\n- [ ] All code chunks run without errors\n- [ ] All \"[Fill this in]\" prompts have been completed\n- [ ] Tables are properly formatted and readable\n- [ ] Executive summary addresses all four required components\n- [ ] Portfolio navigation includes this assignment\n- [ ] Census API key is properly set \n- [ ] Document renders correctly to HTML\n\n**Remember:** Submit your portfolio URL on Canvas, not the file itself. Your assignment should be accessible at `your-portfolio-url/assignments/assignment_1/your_file_name.html`\"\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}